export const COMPONENT_MAP = {
  REST_APPLICATION: Symbol(),
  LOGGER: Symbol(),
  CONFIG: Symbol(),
  DATABESE_CLIENT: Symbol(),
  USER_SERVICE: Symbol(),
  USER_MODEL: Symbol(),
  USER_CONTROLLER: Symbol(),
  OFFER_SERVICE: Symbol(),
  OFFER_MODEL: Symbol(),
  OFFER_CONTROLLER: Symbol(),
  COMMENT_SERVICE: Symbol(),
  COMMENT_MODEL: Symbol(),
  COMMENT_CONTROLLER: Symbol(),
  AUTH_SERVICE: Symbol(),
  AUTH_CONTROLLER: Symbol(),
  EXCEPTION_FILTER: Symbol(),
  AUTH_EXCEPTION_FILTER: Symbol(),
  HTTP_EXCEPTION_FILTER: Symbol(),
  VALIDATION_EXCEPTION_FILTER: Symbol(),
} as const;
